### PR TITLE
changing golib version to 2.4.1 as v3.x has incorrect thrfit import

### PR DESCRIPTION
**Pull request by jgheewala**
method causing upstream projects to fail during compilation.

issue:

golib/go.mod thrift import module is not correct so with following
change in golib/go.mod

replace git.apache.org/thrift.git => github.com/signalfx/thrift v0.0.0-20181211001559-3838fa316492

downstream projects is throwing below error

$ grep -R signalfx/thrift *
go.mod:replace git.apache.org/thrift.git => github.com/signalfx/thrift v0.0.0-20181211001559-3838fa316492
go.sum:github.com/signalfx/thrift v0.0.0-20181211001559-3838fa316492/go.mod h1:Xv29nl9fxdk0hmeqcUHgAZZwvYrOhduNW+9qk4H+6K0=

fix: temporarily move sapm-proto to point github.com/signalfx/golib v2.4.1-0.20190712201320-24bdfeda7f24+incompatible
update golib with the new sapm-proto version and then move sapm-proto
back to v3.1.0 so that it picks up correct thrift path

test: verified golib comiplation by adding replace upstream sapm-proto to
../sapm-proto

### CODE REVIEW

**Comment by keitwb** [comment]
@jgheewala this module and golib have a circular dependency.  That might be part of the problem you are running into.  In either case it seems like downgrading golib is the wrong way to go.

**Comment by jgheewala** [comment]
@keitwb this downgrading is temporary. I want to make sure that we can get this pushed in... update golib to this version make the changes necessary for thrift and then move sapm-proto back to golib/v3

**Comment by tigrannajaryan** [comment]
@owais you want to have a look.

**Comment by owais** [comment]
I suggest moving the translator package to golib to get rid of the circular dep. It's used by only SignalFx agent anyway through golib so it doesn't have live here.

**Comment by owais** [comment]
That way sapm-proto will not have to depend on golib and we'll only have a one way dependency. Only golib will depend on sapm-proto.

**Comment by jgheewala** [comment]
@owais let me see if i can make that change..

**Comment by jgheewala** [comment]
@owais seems like i would have to move gen folder too will do taht

**Comment by jgheewala** [comment]
https://github.com/signalfx/sapm-proto/pull/13

**Pull request closed without merging**
