### PR TITLE
Update github.com/jaegertracing/jaeger to v1.20.0

### PR DESCRIPTION
**Pull request by tigrannajaryan**
Fixes https://github.com/signalfx/sapm-proto/issues/37

Jaeger before version 1.18.1 has known vulnerability.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Note: I accidentally pushed this change directly to master in 74d64766312ba3a1da93b8b27873a0005855b089 and then reverted it in e23a3155ace6882e30a5b9e90a63ecab74afb158.

**Comment by tigrannajaryan** [comment]
@bogdandrutu I see https://github.com/signalfx/sapm-proto/pull/36 was merged previously. Please comment. This update is for a security fix https://github.com/signalfx/sapm-proto/issues/37 (arguably we may not be actually affected, I did not check).

**Comment by jgheewala** [comment]
@tigrannajaryan if there is a thrift update then we cannot merge this changes and use on ingest tier.

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Per discussion with @mdubbyap now this is safe

**Pull request merged**
